# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

#
name: Docker Image CI

# This workflow runs when any of the following occur:
# - A push is made to a branch called `main` or `seed`
# - A tag starting with "v" is created
# - A pull request is created or updated
on:
  workflow_dispatch:
  push:
  #   branches:
  #     - main
    tags:
      - imagerelease-*
  pull_request:
env:
  IMAGE_NAME: realhf-vllm
#
jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      #
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Restart docker
        run: sudo service docker restart
      - uses: actions/checkout@v4

      - name: Show disk space
        run: |
          echo "Free space:"
          df -h
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build builds/vllm --file builds/vllm/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"   --build-arg SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }} --build-arg SCCACHE_REGION=${{ secrets.SCCACHE_REGION }} --build-arg SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }} --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg SCCACHE_INIT_FLAG="yes"

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # This strips the git ref prefix from the version.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          SHORTHASH=$(echo "${{ github.sha }}" | cut -c 1-8)
          DATESTRING=$(date +"%Y%m%d")
          # This strips the "v" prefix from the tag name.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^imagerelease-//')
          # This uses the Docker `latest` tag convention.
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo DATESTRING=$DATESTRING
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:nightly-$DATESTRING-$SHORTHASH
          docker tag $IMAGE_NAME $IMAGE_ID:nightly-runs-${GITHUB_RUN_ID}

          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:nightly-$DATESTRING-$SHORTHASH
          docker push $IMAGE_ID:nightly-runs-${GITHUB_RUN_ID}
          echo "---Image Products---"
          echo $IMAGE_ID:$VERSION
          echo $IMAGE_ID:nightly-$DATESTRING-$SHORTHASH
          echo $IMAGE_ID:nightly-runs-${GITHUB_RUN_ID}


